### ISSUE TITLE
Add LICENSE file for the project.

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/ToDoist#5]

**Comment by tanvimoharir** [comment]
@Pranav016 Please let me know if I can take this up. Thanks.

**Comment by Pranav016** [comment]
> @Pranav016 Please let me know if I can take this up. Thanks.

Sure 😄

**Comment by tanvimoharir** [comment]
PR #6

**Comment by Pranav016** [comment]
Solved via #9
